minetestdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'minetestdb'
urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    # pages
    url(r'^mods', include('mods.urls')),
    url(r'^servers', include('servers.urls')),
    url(r'^users', include('users.urls')),
    url(r'^subgames', views.comingsoon),
    url(r'^texturepacks', views.comingsoon),
    url(r'^skins', views.comingsoon),

    # other stuff
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

mods/urls.py
from django.conf.urls import url

from . import views

app_name = 'mods'
urlpatterns = [
    url(r'^/$', views.index, name='index'),

    # NOTE:
    # r'^/(?P<name>\w+)/detail' matches all alphanumeric, no whitespace chars
    # the current implementation matches all characters
    #
    # IF YOU EVER HAVE THIS PROBLEM AGAIN RESEARCH YOUR REGEX:
    #	https://docs.python.org/3/howto/regex.html
    #	https://docs.python.org/3/library/re.html
    #
    url(r'^/(?P<name>.(?s)+)/detail', views.detail, name='detail'),
    url(r'^-new/$', views.new, name='new'),
]

servers/urls.py
from django.conf.urls import url

from . import views

app_name = 'servers'
urlpatterns = [
    url(r'^/$', views.index, name='index'),

    # NOTE:
    # r'^/(?P<name>\w+)/detail' matches all alphanumeric, no whitespace chars
    # the current implementation matches all characters
    #
    # IF YOU EVER HAVE THIS PROBLEM AGAIN RESEARCH YOUR REGEX:
    #	https://docs.python.org/3/howto/regex.html
    #	https://docs.python.org/3/library/re.html
    #
    url(r'^/(?P<name>.(?s)+)/detail', views.detail, name='detail'),
    url(r'^-new/$', views.new, name='new'),
    url(r'^/(?P<name>.(?s)+)/edit', views.edit, name='edit'),
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^/$', views.index, name='index'),
    url(r'^/(?P<username>\w+)/$', views.detail, name='detail'),
    url(r'^-profile/$', views.profile, name='profile'),
    url(r'^-logout/', views.logout_view, name='logout'),
    url(r'^-login/', views.login_view, name='login'),
    url(r'^-password/$', views.change_password, name='change_password'),
    url(r'^-contact/$', views.change_contact, name='change_contact'),
]

servers/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
#END CONSTRUCTORS AND LIBS


# NOTE:
#	Don't forget >>> models.Model.id and models.Model.pk
#
# are unique identifiers to the database.
# don't try and make a uuid though, it breaks things like that
# object_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
#
# So actually... when using IDs these fields are autogenerated by default
# id = ...
# pk = ...
#
# However, note that they're automatically set to the instance number
# in the table it's data is contained within.
#
# BUG: *** FIXED ***
# inadvertently created an extra bug because ID didn't get researched properly
# too well and was to use id as a uuid... but it's fixed now lol.
#
# So now you can:
#	Server.objects.all()[n].unique_id
#
# and use that to relate POST data to SQL data and properly display
# the relation within the templates' output.
# FIX FOR ISSUE #4

# NOTE: this file's inherited global models
from universal.models import (
    Version
)

class Tag(models.Model):
    objattr = models.CharField(max_length=4, default="tags")
    #pk = ...
    #id = ...
    value = models.CharField(max_length=20)
    def __str__(self):
        return self.value

class Server(models.Model):
    #pk = ...
    #id = ...
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, None, null=True)
    address = models.URLField(max_length=200, null=True)
    website = models.URLField(max_length=200, null=True)
    description = models.TextField(null=True)
    votes = models.IntegerField(default=0, null=True)
    mt_version = models.ForeignKey(Version, None, null=True)
    tags = models.ManyToManyField(Tag, verbose_name='Tags', blank=True)

servers/forms.py
from django.forms import ModelForm

from .models import Server
from django import forms
from .models import Tag


class NewServerForm(ModelForm):

    class Meta:
        model = Server
        fields = ['name', 'address', 'website', 'description', 'mt_version', 'tags']
        exclude = ['owner']

servers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
#END CONSTRUCTORS AND LIBS

# NOTE: Global Imports
from universal import (
    #Version (Redundant)
    dynamic_sort
)

# NOTE: Local Imports
from .models import (
    Server,
    Tag,
    Version
)
from .forms import (
    NewServerForm
)


def index(request):
    tags = Tag.objects.all()
    versions = Version.objects.all()
    servers = Server.objects.all()

    # Here, we sort the post data.
    # It's alot more efficient to do it here than from within the templates
    #
    if request.method == 'POST':
        post = request.POST.dict()
        servers = dynamic_sort(post, servers, [Tag, Version])
    else:
        post = {}

    filters = {
        'Minetest Version': versions,			# Available Version Filters
        'Tags': tags 							# Available Filter Tags
    }

    # This is just a rebinding of variables in python scope, to template scope.
    context = {
        'post': post,							# Raw Post
        'servers': servers,				# Available Servers
        'filters': filters						# All Available Filters
    }
    return render(request, 'servers/index.html', context)


def detail(request, name):
    server = get_object_or_404(Server, name=name)
    return render(request, 'servers/detail.html', {'server': server})


def new(request):
    if request.method == 'POST':
        form = NewServerForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.owner = request.user
            model.save()
            form.save_m2m()
            return render(request, 'servers/confirm.html', {'form': form})
    else:
        form = NewServerForm()

    return render(request, 'servers/create.html', {'form': form})


def edit(request, name):
    server = get_object_or_404(Server, name=name)
    if request.method == 'POST':
        form = NewServerForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.owner = request.user
            model.save()
            form.save_m2m()
            return render(request, 'servers/confirm.html', {'form': form})
    else:
        form = NewServerForm({'name': server.name,
                              'address': server.address,
                              'website': server.website,
                              'description': server.description,
                              'mt_version': server.mt_version,
                              'tags': server.tags
                              })

    return render(request, 'servers/edit.html', {'server': server, 'form': form})

templates/servers/confirm.html
{%  extends "minetestdb/base.html" %}

{%  block content %}

    Success!!!

{%  endblock content %}

templates/servers/create.html
{%  extends "minetestdb/base.html" %}

{% block title %}MTCD New Server{% endblock %}

{%  block content %}

<div class="container">
    server creation page

    <form action="." method="post">
        {{ form.non_field_errors }}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>

{%  endblock %}

templates/servers/detail.html
{%  extends "minetestdb/base.html" %}

{% block title %}MTCD {{ server.name }}{% endblock %}

{%  block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <div class="panel panel-default">
                <div class="panel-heading"><h1>{{ server.name }}</h1></div>
                <div class="panel-body"><div style="white-space: pre-wrap;">{{ server.description }}</div></div>
            </div>
        </div>
        <div class="col-sm-3">
            <div>
                {% if server in user.stared_servers %}
                <button type="button" class="btn btn-default btn-lg">
                    <span class="glyphicon glyphicon-star" aria-hidden="true"> Stars count</span>
                </button>
                {% else %}
                <button type="button" class="btn btn-default btn-lg">
                    <span class="glyphicon glyphicon-star-empty" aria-hidden="true"> Stars count</span>
                </button>
                {% endif %}
            </div><br>
            {% if server.owner == user %}
                <a href="{% url 'servers:edit' server.name %}">
                    <button type="button" class="btn btn-default">Edit your posting</button>
                </a><br><br>
            {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">Address</div>
                <div class="panel-body">{{ server.address }}</div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Server Owner</div>
                <div class="panel-body"><a href="{% url 'users:detail' server.owner %}">{{ server.owner }}</a></div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Minetest Version</div>
                <div class="panel-body">{{ server.mt_version }}</div>
            </div>
            {% if server.website %}
            <div class="panel panel-default">
                <div class="panel-heading">Website</div>
                <div class="panel-body"><a href="{{ server.website }}">{{ server.website }}</a></div>
            </div>
            {%  endif %}
            {% if server.tags %}
            <div class="panel panel-default">
                <div class="panel-heading">Tags</div>
                <div class="panel-body">
                    {%  for tag in server.tags.all %}
                        <span class="label label-default">{{ tag }}</span>
                    {% endfor %}
                </div>
            </div>
            {%  endif %}
            <div class="panel panel-default">
                <div class="panel-heading">Server Status</div>
                <div class="panel-body">Future Server Status widget goes here</div>
            </div>
        </div>
    </div>
</div>

{%  endblock %}

templates/servers/edit.html
{%  extends "minetestdb/base.html" %}

{% block title %}MTCD New Server{% endblock %}

{%  block content %}

<div class="container">
    server edit page

    <form action="." method="post">
        {{ form.non_field_errors }}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>

{%  endblock %}

templates/servers/index.html
{%  extends "minetestdb/base.html" %}

{% block title %}MTCD Servers{% endblock %}

{%  block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                {% if user.is_authenticated %}
                    <a href="{% url 'servers:new' %}">
                        <button type="button" class="btn btn-default">Create a new server posting</button>
                    </a><br><br>
                {%  endif %}
                <form action="." method="post">
                {% csrf_token %}
                    {% comment %}
                        <div class="form-group">
                            <div class="panel panel-default">
                                <div class="panel-heading">Sort By:</div>
                                <div class="panel-body">
                                    <div class="dropdown">
                                        <select class="form-control" id="sort" name="sort">
                                            <option>Oldest</option>
                                            <option>Newest</option>
                                            <option>Most Stars</option>
                                            <option>????</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endcomment %}
                    {% for ftypename, ftype in filters.items %}
                        {% if ftype %}
                            <div class="form-group">
                                <div class="panel panel-default">
                                    <div class="panel-heading">{{ ftypename }} </div>
                                    <div class="panel-body">
                                        {% for filter in ftype %}
                                            <div class="checkbox">
                                                <label>
                                                    {% with strid=filter.id|stringformat:"i" %}
                                                        {% with identifier=ftype.objattr|add:strid %}
                                                            <input
                                                                type="checkbox"
                                                                name="{{ identifier }}"
                                                                {% if identifier in post.keys %}
                                                                    checked="checked"
                                                                {% endif %}
                                                            >
                                                            {{ filter }}
                                                        {% endwith %}
                                                    {% endwith %}
                                                </label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <input type="submit" class="btn btn-default" value="Apply Filters">
                </form>
            </div>
            <div class="col-sm-9">
                {% if servers %}
                    {% for server in servers %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="{% url 'servers:detail' server.name|escape %}">{{ server.name }}</a>
                                <span class="pull-right">{{ server.address }}</span>
                            </div>
                            <div class="panel-body">
                                <p>{{ server.description|truncatechars:250 }}</p>
                                    {%  for tag in server.tags.all %}
                                        <span class="label label-default">{{ tag }}</span>
                                    {% endfor %}
                                <span class="pull-right">MT Version: {{ server.mt_version }}</span>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No servers are available.</p>
                {% endif %}
                {% comment %}
                    {% for i, k in post.items %}
                        {{ i }} and {{ k }} <br>
                    {%  endfor %}
                {% endcomment %}
            </div>
        </div>
    </div>
{% endblock %}