minetestdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'minetestdb'
urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    # pages
    url(r'^mods', include('mods.urls')),
    url(r'^servers', include('servers.urls')),
    url(r'^users', include('users.urls')),
    url(r'^subgames', views.comingsoon),
    url(r'^texturepacks', views.comingsoon),
    url(r'^skins', views.comingsoon),

    # other stuff
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

mods/urls.py
from django.conf.urls import url

from . import views

app_name = 'mods'
urlpatterns = [
    url(r'^/$', views.index, name='index'),

    # NOTE:
    # r'^/(?P<name>\w+)/detail' matches all alphanumeric, no whitespace chars
    # the current implementation matches all characters
    #
    # IF YOU EVER HAVE THIS PROBLEM AGAIN RESEARCH YOUR REGEX:
    #	https://docs.python.org/3/howto/regex.html
    #	https://docs.python.org/3/library/re.html
    #
    url(r'^/(?P<name>.(?s)+)/detail', views.detail, name='detail'),
    url(r'^-new/$', views.new, name='new'),
]

servers/urls.py
from django.conf.urls import url

from . import views

app_name = 'servers'
urlpatterns = [
    url(r'^/$', views.index, name='index'),

    # NOTE:
    # r'^/(?P<name>\w+)/detail' matches all alphanumeric, no whitespace chars
    # the current implementation matches all characters
    #
    # IF YOU EVER HAVE THIS PROBLEM AGAIN RESEARCH YOUR REGEX:
    #	https://docs.python.org/3/howto/regex.html
    #	https://docs.python.org/3/library/re.html
    #
    url(r'^/(?P<name>.(?s)+)/detail', views.detail, name='detail'),
    url(r'^-new/$', views.new, name='new'),
    url(r'^/(?P<name>.(?s)+)/edit', views.edit, name='edit'),
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^/$', views.index, name='index'),
    url(r'^/(?P<username>\w+)/$', views.detail, name='detail'),
    url(r'^-profile/$', views.profile, name='profile'),
    url(r'^-logout/', views.logout_view, name='logout'),
    url(r'^-login/', views.login_view, name='login'),
    url(r'^-password/$', views.change_password, name='change_password'),
    url(r'^-contact/$', views.change_contact, name='change_contact'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from servers.models import Server
from mods.models import Mod


class Notification(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    stared_mods = models.ManyToManyField(Mod, verbose_name='Mods',  blank=True)
    stared_servers = models.ManyToManyField(Server, verbose_name='Servers',  blank=True)
    notifications = models.ManyToManyField(Notification, verbose_name='Notification', blank=True)
    # ----- Communication -----
    github = models.TextField(max_length=50, blank=True)
    irc = models.TextField(max_length=50, blank=True)
    discord = models.TextField(max_length=50, blank=True)
    skype = models.TextField(max_length=50, blank=True)
    ingame = models.TextField(max_length=50, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

users/forms.py
from django import forms



class ChangeContactForm(forms.Form):
    github = forms.CharField(label='GitHub', max_length=50, required=False)
    irc = forms.CharField(label='IRC', max_length=50, required=False)
    discord = forms.CharField(label='Discord', max_length=50, required=False)
    skype = forms.CharField(label='skype', max_length=50, required=False)
    ingame = forms.CharField(label='Ingame', max_length=50, required=False)

users/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from servers.models import Server
from mods.models import Mod
from users.forms import ChangeContactForm


# Lists registered users
def index(request):
    user_list = User.objects.all()
    context = {'user_list': user_list}
    return render(request, 'users/index.html', context)


# Displays information on a user
def detail(request, username):
    user = get_object_or_404(User, username=username)
    server_list = Server.objects.filter(owner=user)
    mod_list = Mod.objects.filter(author=user)
    return render(request, 'users/detail.html', {'duser': user,
                                                 'servers': server_list,
                                                 'mods': mod_list})


# Allows user to edit their profile
def profile(request):
    if not request.user.is_authenticated:
        return redirect('/login/')
    else:
        return render(request, 'users/profile.html')


def logout_view(self, request):
    logout(request)
    redirect("/")
    return


def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        redirect("/")
    else:
        redirect("/")


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('users:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/change_password.html', {
        'form': form
    })


def change_contact(request):
    if request.method == 'POST':
        form = ChangeContactForm(request.POST)
        if form.is_valid():
            prof = request.user.profile
            if form.cleaned_data['github']:
                prof.github = form.cleaned_data['github']
            if form.cleaned_data['irc']:
                prof.github = form.cleaned_data['irc']
            if form.cleaned_data['discord']:
                prof.github = form.cleaned_data['discord']
            if form.cleaned_data['skype']:
                prof.github = form.cleaned_data['skype']
            if form.cleaned_data['ingame']:
                prof.github = form.cleaned_data['ingame']
            prof.save()
            return redirect('users:change_contact')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = ChangeContactForm()
    return render(request, 'users/change_contact.html', {
        'form': form.as_p()
    })

templates/users/change_contact.html
{%  extends "users/profile.html" %}

{%  block profile %}

    <div class="container">
        <h2>Change Contact Information</h2>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="container">
        <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
        </form>
    </div>

{%  endblock %}

templates/users/change_password.html
{%  extends "users/profile.html" %}

{%  block profile %}

    <div class="container">
        <h2>Change Password</h2>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="container">
        <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
        </form>
    </div>

{%  endblock %}

templates/users/detail.html
{%  extends "minetestdb/base.html" %}

{%  block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-heading"><h1>{{ duser.username }}</h1></div>
            </div>
            {% if duser == user %}
                <a href="{% url 'users:profile' %}">
                    <button type="button" class="btn btn-default">Edit your profile</button>
                </a><br><br>
            {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">Biography</div>
                <div class="panel-body" style="white-space: pre-wrap;">{{ duser.profile.bio }}</div>
            </div>
            {% if user.profile.location %}
            <div class="panel panel-default">
                <div class="panel-heading">Location</div>
                <div class="panel-body">{{ duser.profile.location }}</div>
            </div>
            {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">Contact Information</div>
                <div class="panel-body">
                    {% if user.profile.github %}
                        <div><b>GitHub:</b> <a href="http://www.github.com/{{ duser.profile.github }}">{{ duser.profile.github }}</a></div>
                    {% endif %}
                    {% if user.profile.irc %}
                        <div><b>IRC:</b> {{ duser.profile.irc }}</div>
                    {% endif %}
                    {% if user.profile.discord %}
                        <div><b>Discord:</b> {{ duser.profile.discord }}</div>
                    {% endif %}
                    {% if user.profile.skype %}
                        <div><b>Skype:</b> {{ duser.profile.skype }}</div>
                    {% endif %}
                    {% if user.profile.ingame %}
                        <div><b>In Game:</b> {{ duser.profile.ingame }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading"><h1>Content</h1></div>
                <div class="panel-body">
                    <div class="row">
                        {% for server in servers %}
                        <div class="col-sm-4">
                            <div>Server</div>
                            <div><a href="{% url 'servers:detail' server.name %}">{{ server.name }}</a></div>
                        </div>
                        {% endfor %}
                        {% for mod in mods %}
                        <div class="col-sm-4">
                            <div>Mod</div>
                            <div><a href="{% url 'mods:detail' mod.name %}">{{ mod.name }}</a></div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Stars</div>
                <div class="panel-body">
                    <h4>Mods</h4>
                {% if duser.profile.stared_mods.all %}
                    {%  for mod in duser.profile.stared_mods.all %}
                        <div><a href="{% url 'mods:detail' mod.name %}">{{ mod.name }}</a></div>

                    {% endfor %}
                {% else %}
                    You don't have any mods stared yet
                {% endif %}
                    <h4>Servers</h4>
                {% if duser.profile.stared_servers.all %}
                    {%  for server in duser.profile.stared_servers.all %}
                        <div><a href="{% url 'servers:detail' server.name %}">{{ server.name }}</a></div>
                    {% endfor %}
                {% else %}
                    You don't have any servers stared yet
                {% endif %}
                </div>
            </div>
        </div>
</div>

{%  endblock %}

templates/users/index.html
{%  extends "minetestdb/base.html" %}

{%  block content %}
    <div class="container">
        <div class="row">
                {% if user_list %}
                    {% for user in user_list %}
                    <div class="col-sm-3">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="{% url 'users:detail' user.username %}">{{ user.username }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No users are available.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{%  extends "minetestdb/base.html" %}

{%  block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="container">
                    <h1>{{ user }}</h1>
                </div>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:change_password' %}">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:change_contact' %}">Change Contact Information</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-9">
                {% block profile %}Something didn't load . . . Try reloading . . . {% endblock %}
            </div>
        </div>
    </div>

{%  endblock %}

templates/users/user-widget.html
{% if user.is_authenticated %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            {{  user.username }} <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'users:detail' user.username %}">Profile</a></li>
            <li><a href="#">Messages</a></li>
            <li><a href="#">Stars</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/logout/">Logout</a></li>
        </ul>
    </li>
{%  else %}
    <li><a href="/login/">Login</a></li>
{%  endif %}