minetestdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'minetestdb'
urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    # pages
    url(r'^mods', include('mods.urls')),
    url(r'^servers', include('servers.urls')),
    url(r'^users', include('users.urls')),
    url(r'^subgames', views.comingsoon),
    url(r'^texturepacks', views.comingsoon),
    url(r'^skins', views.comingsoon),

    # other stuff
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
]

mods/urls.py
from django.conf.urls import url

from . import views

app_name = 'mods'
urlpatterns = [
    url(r'^/$', views.index, name='index'),

    # NOTE:
    # r'^/(?P<name>\w+)/detail' matches all alphanumeric, no whitespace chars
    # the current implementation matches all characters
    #
    # IF YOU EVER HAVE THIS PROBLEM AGAIN RESEARCH YOUR REGEX:
    #	https://docs.python.org/3/howto/regex.html
    #	https://docs.python.org/3/library/re.html
    #
    url(r'^/(?P<name>.(?s)+)/detail', views.detail, name='detail'),
    url(r'^-new/$', views.new, name='new'),
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^/$', views.index, name='index'),
    url(r'^/(?P<username>\w+)/$', views.detail, name='detail'),
    url(r'^-profile/$', views.profile, name='profile'),
    url(r'^-logout/', views.logout_view, name='logout'),
    url(r'^-login/', views.login_view, name='login'),
    url(r'^-password/$', views.change_password, name='change_password'),
    url(r'^-contact/$', views.change_contact, name='change_contact'),
]

mods/models.py
from django.db import models
from django.contrib.auth.models import User
#END CONSTRUCTORS AND LIBS


# NOTE: this file's inherited global models
from universal.models import (
    Version
)

class Tag(models.Model):
    objattr = models.CharField(max_length=4, default="tags") #NOTE DO NOT EDIT
    #pk = ...
    #id = ...
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Mod(models.Model):
    objattr = models.CharField(max_length=4, default="mods") #NOTE DO NOT EDIT
    name = models.CharField(max_length=200)
    author = models.ForeignKey(User, None)
    git = models.URLField(max_length=200, null=True)
    download = models.URLField(max_length=200, null=True)
    mt_version = models.OneToOneField(Version, None, verbose_name='Minetest Version', default=None)
    description = models.TextField()
    tags = models.ManyToManyField(Tag, verbose_name='Tags',  blank=True)

mods/forms.py
from django.forms import ModelForm
from .models import Mod


class NewModForm(ModelForm):

    class Meta:
        model = Mod
        fields = ['name', 'git', 'download', 'mt_version', 'description', 'tags']
        exclude = ['author']

mods/views.py
from django.shortcuts import get_object_or_404, render
#END CONSTRUCTORS AND LIBS

# NOTE: Global Imports
from universal import (
    # Version # don't need this here because it's inherited through our local .models
    dynamic_sort
)

# NOTE: Local Imports
from .models import (
    Mod,
    Tag,
    Version
)
from .forms import (
    NewModForm
)


def index(request):
    mods = Mod.objects.all()
    tags = Tag.objects.all()
    versions = Version.objects.all()

    # Here, we sort the post data.
    # It's alot more efficient to do it here than from within the templates
    #
    if request.method == 'POST':
        post = request.POST.dict()
        mods = dynamic_sort(post, mods, [Tag, Version])
    else:
        post = {}


    filters = {
        'Minetest Version': versions,			# Available Version Filters
        'Tags': tags 							# Available Filter Tags
    }

    # This is just a rebinding of variables in python scope, to template scope.
    context = {
        'post': post,							# Raw Post
        'mods': mods,							# Available Mods
        'filters': filters						# All Available Filters
    }
    return render(request, 'mods/index.html', context)


def detail(request, name):
    mod = get_object_or_404(Mod, name=name)
    return render(request, 'mods/detail.html', {'mod': mod})


def new(request):
    if request.method == 'POST':
        form = NewModForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.author = request.user
            page = model.name
            model.save()
            return render(request, 'mods/' + page, {'form': form})
    else:
        form = NewModForm()

    return render(request, 'mods/create.html', {'form': form})


def edit(request, name):
    server = get_object_or_404(Server, name=name)
    form = NewServerForm(initial={'name': server.name,
                                  'address': server.address,
                                  'website': server.website,
                                  'description': server.description,
                                  'mt_version': server.mt_version,
                                  'tags': server.tags
                                  })
    return render(request, 'servers/edit.html', {'server': server, 'form': form})

templates/mods/create.html
{%  extends "minetestdb/base.html" %}

{% block title %}MTCD New Mod Posting{% endblock %}

{%  block content %}

<div class="container">
    Mod post creation page

    <form action="." method="post">
        {{ form.non_field_errors }}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>

{%  endblock %}

templates/mods/detail.html
{%  extends "minetestdb/base.html" %}

{% block title %}MTCD {{ mod.name }}{% endblock %}

{%  block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <div class="panel panel-default">
                <div class="panel-heading"><h1>{{ mod.name }}</h1></div>
                <div class="panel-body"><div style="white-space: pre-wrap;">{{ mod.description }}</div></div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="panel panel-default">
                <div class="panel-heading">Download</div>
                <div class="panel-body"><a href="{{ mod.download }}">{{ mod.download }}</a></div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Mod Author</div>
                <div class="panel-body"><a href="{% url 'users:detail' mod.author %}">{{ mod.author }}</a></div>
            </div>
            {% if mod.git %}
            <div class="panel panel-default">
                <div class="panel-heading">Git Repo</div>
                <div class="panel-body"><a href="{{ mod.git }}">{{ mod.git }}</a></div>
            </div>
            {%  endif %}
            {% if mod.tags %}
            <div class="panel panel-default">
                <div class="panel-heading">Tags</div>
                <div class="panel-body">
                    {%  for tag in mod.tags.all %}
                        <span class="label label-default">{{ tag }}</span>
                    {% endfor %}
                </div>
            </div>
            {%  endif %}
        </div>
    </div>
</div>

{%  endblock %}

templates/mods/index.html
{%  extends "minetestdb/base.html" %}

{% block title %}MTCD Mods{% endblock %}

{%  block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                {% if user.is_authenticated %}
                    <a href="{% url 'mods:new' %}">
                        <button type="button" class="btn btn-default">Create a new mod posting</button>
                    </a><br><br>
                {%  endif %}
                <form action="." method="post">
                {% csrf_token %}
                    {% comment %}
                        <div class="form-group">
                            <div class="panel panel-default">
                                <div class="panel-heading">Sort By:</div>
                                <div class="panel-body">
                                    <div class="dropdown">
                                        <select class="form-control" id="sort" name="sort">
                                            <option>Oldest</option>
                                            <option>Newest</option>
                                            <option>Most Stars</option>
                                            <option>????</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endcomment %}
                    {% for ftypename, ftype in filters.items %}
                        {% if ftype %}
                            <div class="form-group">
                                <div class="panel panel-default">
                                    <div class="panel-heading">{{ ftypename }} </div>
                                    <div class="panel-body">
                                        {% for filter in ftype %}
                                            <div class="checkbox">
                                                <label>
                                                    {% with strid=filter.id|stringformat:"i" %}
                                                        {% with identifier=filter.objattr|add:strid %}
                                                            <input
                                                                type="checkbox"
                                                                name="{{ identifier }}"
                                                                {% if identifier in post.keys %}
                                                                    checked="checked"
                                                                {% endif %}
                                                            >
                                                            {{ filter }}
                                                        {% endwith %}
                                                    {% endwith %}
                                                </label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <input type="submit" class="btn btn-default" value="Apply Filters">
                </form>
            </div>
            <div class="col-sm-9">
                {% if current_mod_list %}
                    {% for mod in current_mod_list %}

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="{% url 'mods:detail' mod.name %}">{{ mod.name }}</a>
                                <span class="pull-right">{{ mod.author }}</span>
                            </div>
                            <div class="panel-body">
                                <p>{{ mod.description|truncatechars:250 }}</p>
                                    {%  for tag in mod.tags.all %}
                                        <span class="label label-default">{{ tag }}</span>
                                    {% endfor %}

                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No mods are available.</p>
                {% endif %}
{% comment %}                {% for i, k in post.items %}
                    {{ i }} and {{ k }} <br>
                {%  endfor %}{% endcomment %}
            </div>
        </div>
    </div>
{% endblock %}